remnants_report:
  cron: '0 9 * * * Asia/Vladivostok'
  class: 'RemnantsReportMailingJob'
  queue: 'reports'
  active_job: true

sales_report:
  cron: '45 9 * * * Asia/Vladivostok'
  class: 'DailySalesReportMailingJob'
  queue: 'reports'
  active_job: true

sales_import:
  cron: '0 22 * * * Asia/Vladivostok'
  class: 'SalesImportJob'
  queue: 'critical'
  active_job: true

mark_expired_faults:
  cron: '0 0 1 * * Asia/Vladivostok'
  class: 'MarkExpiredFaultsJob'
  queue: 'default'
  active_job: true

birthday_announcements:
  cron: '0 8 * * * Asia/Vladivostok'
  class: 'BirthdayAnnouncementsJob'
  queue: 'default'
  active_job: true

bad_review_announcements:
  cron: '0 8 * * * Asia/Vladivostok'
  class: 'BadReviewAnnouncementsJob'
  queue: 'default'
  active_job: true