require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GiftCertificatesController do

  # This should return the minimal set of attributes required to create a valid
  # GiftCertificate. As you add validations to GiftCertificate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "number" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GiftCertificatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gift_certificates as @gift_certificates" do
      gift_certificate = GiftCertificate.create! valid_attributes
      get :index, params: {}, session: valid_session
      assigns(:gift_certificates).should eq([gift_certificate])
    end
  end

  describe "GET show" do
    it "assigns the requested gift_certificate as @gift_certificate" do
      gift_certificate = GiftCertificate.create! valid_attributes
      get :show, params: {:id => gift_certificate.to_param}, session: valid_session
      assigns(:gift_certificate).should eq(gift_certificate)
    end
  end

  describe "GET new" do
    it "assigns a new gift_certificate as @gift_certificate" do
      get :new, params: {}, session: valid_session
      assigns(:gift_certificate).should be_a_new(GiftCertificate)
    end
  end

  describe "GET edit" do
    it "assigns the requested gift_certificate as @gift_certificate" do
      gift_certificate = GiftCertificate.create! valid_attributes
      get :edit, params: {:id => gift_certificate.to_param}, session: valid_session
      assigns(:gift_certificate).should eq(gift_certificate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GiftCertificate" do
        expect {
          post :create, params: {:gift_certificate => valid_attributes}, session: valid_session
        }.to change(GiftCertificate, :count).by(1)
      end

      it "assigns a newly created gift_certificate as @gift_certificate" do
        post :create, params: {:gift_certificate => valid_attributes}, session: valid_session
        assigns(:gift_certificate).should be_a(GiftCertificate)
        assigns(:gift_certificate).should be_persisted
      end

      it "redirects to the created gift_certificate" do
        post :create, params: {:gift_certificate => valid_attributes}, session: valid_session
        response.should redirect_to(GiftCertificate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gift_certificate as @gift_certificate" do
        # Trigger the behavior that occurs when invalid params are submitted
        GiftCertificate.any_instance.stub(:save).and_return(false)
        post :create, params: {:gift_certificate => { "number" => "invalid value" }}, session: valid_session
        assigns(:gift_certificate).should be_a_new(GiftCertificate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GiftCertificate.any_instance.stub(:save).and_return(false)
        post :create, params: {:gift_certificate => { "number" => "invalid value" }}, session: valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gift_certificate" do
        gift_certificate = GiftCertificate.create! valid_attributes
        # Assuming there are no other gift_certificates in the database, this
        # specifies that the GiftCertificate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GiftCertificate.any_instance.should_receive(:update_attributes).with({ "number" => "MyString" })
        put :update, params: {:id => gift_certificate.to_param, :gift_certificate => { "number" => "MyString" }}, session: valid_session
      end

      it "assigns the requested gift_certificate as @gift_certificate" do
        gift_certificate = GiftCertificate.create! valid_attributes
        put :update, params: {:id => gift_certificate.to_param, :gift_certificate => valid_attributes}, session: valid_session
        assigns(:gift_certificate).should eq(gift_certificate)
      end

      it "redirects to the gift_certificate" do
        gift_certificate = GiftCertificate.create! valid_attributes
        put :update, params: {:id => gift_certificate.to_param, :gift_certificate => valid_attributes}, session: valid_session
        response.should redirect_to(gift_certificate)
      end
    end

    describe "with invalid params" do
      it "assigns the gift_certificate as @gift_certificate" do
        gift_certificate = GiftCertificate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GiftCertificate.any_instance.stub(:save).and_return(false)
        put :update, params: {:id => gift_certificate.to_param, :gift_certificate => { "number" => "invalid value" }}, session: valid_session
        assigns(:gift_certificate).should eq(gift_certificate)
      end

      it "re-renders the 'edit' template" do
        gift_certificate = GiftCertificate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GiftCertificate.any_instance.stub(:save).and_return(false)
        put :update, params: {:id => gift_certificate.to_param, :gift_certificate => { "number" => "invalid value" }}, session: valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gift_certificate" do
      gift_certificate = GiftCertificate.create! valid_attributes
      expect {
        delete :destroy, params: {:id => gift_certificate.to_param}, session: valid_session
      }.to change(GiftCertificate, :count).by(-1)
    end

    it "redirects to the gift_certificates list" do
      gift_certificate = GiftCertificate.create! valid_attributes
      delete :destroy, params: {:id => gift_certificate.to_param}, session: valid_session
      response.should redirect_to(gift_certificates_url)
    end
  end

end
