require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstallmentPlansController do

  # This should return the minimal set of attributes required to create a valid
  # InstallmentPlan. As you add validations to InstallmentPlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstallmentPlansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all installment_plans as @installment_plans" do
      installment_plan = InstallmentPlan.create! valid_attributes
      get :index, params: {}, session: valid_session
      assigns(:installment_plans).should eq([installment_plan])
    end
  end

  describe "GET show" do
    it "assigns the requested installment_plan as @installment_plan" do
      installment_plan = InstallmentPlan.create! valid_attributes
      get :show, params: {:id => installment_plan.to_param}, session: valid_session
      assigns(:installment_plan).should eq(installment_plan)
    end
  end

  describe "GET new" do
    it "assigns a new installment_plan as @installment_plan" do
      get :new, params: {}, session: valid_session
      assigns(:installment_plan).should be_a_new(InstallmentPlan)
    end
  end

  describe "GET edit" do
    it "assigns the requested installment_plan as @installment_plan" do
      installment_plan = InstallmentPlan.create! valid_attributes
      get :edit, params: {:id => installment_plan.to_param}, session: valid_session
      assigns(:installment_plan).should eq(installment_plan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstallmentPlan" do
        expect {
          post :create, params: {:installment_plan => valid_attributes}, session: valid_session
        }.to change(InstallmentPlan, :count).by(1)
      end

      it "assigns a newly created installment_plan as @installment_plan" do
        post :create, params: {:installment_plan => valid_attributes}, session: valid_session
        assigns(:installment_plan).should be_a(InstallmentPlan)
        assigns(:installment_plan).should be_persisted
      end

      it "redirects to the created installment_plan" do
        post :create, params: {:installment_plan => valid_attributes}, session: valid_session
        response.should redirect_to(InstallmentPlan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved installment_plan as @installment_plan" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstallmentPlan.any_instance.stub(:save).and_return(false)
        post :create, params: {:installment_plan => { "user" => "invalid value" }}, session: valid_session
        assigns(:installment_plan).should be_a_new(InstallmentPlan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstallmentPlan.any_instance.stub(:save).and_return(false)
        post :create, params: {:installment_plan => { "user" => "invalid value" }}, session: valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested installment_plan" do
        installment_plan = InstallmentPlan.create! valid_attributes
        # Assuming there are no other installment_plans in the database, this
        # specifies that the InstallmentPlan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstallmentPlan.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, params: {:id => installment_plan.to_param, :installment_plan => { "user" => "" }}, session: valid_session
      end

      it "assigns the requested installment_plan as @installment_plan" do
        installment_plan = InstallmentPlan.create! valid_attributes
        put :update, params: {:id => installment_plan.to_param, :installment_plan => valid_attributes}, session: valid_session
        assigns(:installment_plan).should eq(installment_plan)
      end

      it "redirects to the installment_plan" do
        installment_plan = InstallmentPlan.create! valid_attributes
        put :update, params: {:id => installment_plan.to_param, :installment_plan => valid_attributes}, session: valid_session
        response.should redirect_to(installment_plan)
      end
    end

    describe "with invalid params" do
      it "assigns the installment_plan as @installment_plan" do
        installment_plan = InstallmentPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstallmentPlan.any_instance.stub(:save).and_return(false)
        put :update, params: {:id => installment_plan.to_param, :installment_plan => { "user" => "invalid value" }}, session: valid_session
        assigns(:installment_plan).should eq(installment_plan)
      end

      it "re-renders the 'edit' template" do
        installment_plan = InstallmentPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstallmentPlan.any_instance.stub(:save).and_return(false)
        put :update, params: {:id => installment_plan.to_param, :installment_plan => { "user" => "invalid value" }}, session: valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested installment_plan" do
      installment_plan = InstallmentPlan.create! valid_attributes
      expect {
        delete :destroy, params: {:id => installment_plan.to_param}, session: valid_session
      }.to change(InstallmentPlan, :count).by(-1)
    end

    it "redirects to the installment_plans list" do
      installment_plan = InstallmentPlan.create! valid_attributes
      delete :destroy, params: {:id => installment_plan.to_param}, session: valid_session
      response.should redirect_to(installment_plans_url)
    end
  end

end
