require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RevaluationActsController do

  # This should return the minimal set of attributes required to create a valid
  # RevaluationAct. As you add validations to RevaluationAct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "price_type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RevaluationActsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all revaluation_acts as @revaluation_acts" do
      revaluation_act = RevaluationAct.create! valid_attributes
      get :index, params: {}, session: valid_session
      assigns(:revaluation_acts).should eq([revaluation_act])
    end
  end

  describe "GET show" do
    it "assigns the requested revaluation_act as @revaluation_act" do
      revaluation_act = RevaluationAct.create! valid_attributes
      get :show, params: {:id => revaluation_act.to_param}, session: valid_session
      assigns(:revaluation_act).should eq(revaluation_act)
    end
  end

  describe "GET new" do
    it "assigns a new revaluation_act as @revaluation_act" do
      get :new, params: {}, session: valid_session
      assigns(:revaluation_act).should be_a_new(RevaluationAct)
    end
  end

  describe "GET edit" do
    it "assigns the requested revaluation_act as @revaluation_act" do
      revaluation_act = RevaluationAct.create! valid_attributes
      get :edit, params: {:id => revaluation_act.to_param}, session: valid_session
      assigns(:revaluation_act).should eq(revaluation_act)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RevaluationAct" do
        expect {
          post :create, params: {:revaluation_act => valid_attributes}, session: valid_session
        }.to change(RevaluationAct, :count).by(1)
      end

      it "assigns a newly created revaluation_act as @revaluation_act" do
        post :create, params: {:revaluation_act => valid_attributes}, session: valid_session
        assigns(:revaluation_act).should be_a(RevaluationAct)
        assigns(:revaluation_act).should be_persisted
      end

      it "redirects to the created revaluation_act" do
        post :create, params: {:revaluation_act => valid_attributes}, session: valid_session
        response.should redirect_to(RevaluationAct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved revaluation_act as @revaluation_act" do
        # Trigger the behavior that occurs when invalid params are submitted
        RevaluationAct.any_instance.stub(:save).and_return(false)
        post :create, params: {:revaluation_act => { "price_type" => "invalid value" }}, session: valid_session
        assigns(:revaluation_act).should be_a_new(RevaluationAct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RevaluationAct.any_instance.stub(:save).and_return(false)
        post :create, params: {:revaluation_act => { "price_type" => "invalid value" }}, session: valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested revaluation_act" do
        revaluation_act = RevaluationAct.create! valid_attributes
        # Assuming there are no other revaluation_acts in the database, this
        # specifies that the RevaluationAct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RevaluationAct.any_instance.should_receive(:update_attributes).with({ "price_type" => "" })
        put :update, params: {:id => revaluation_act.to_param, :revaluation_act => { "price_type" => "" }}, session: valid_session
      end

      it "assigns the requested revaluation_act as @revaluation_act" do
        revaluation_act = RevaluationAct.create! valid_attributes
        put :update, params: {:id => revaluation_act.to_param, :revaluation_act => valid_attributes}, session: valid_session
        assigns(:revaluation_act).should eq(revaluation_act)
      end

      it "redirects to the revaluation_act" do
        revaluation_act = RevaluationAct.create! valid_attributes
        put :update, params: {:id => revaluation_act.to_param, :revaluation_act => valid_attributes}, session: valid_session
        response.should redirect_to(revaluation_act)
      end
    end

    describe "with invalid params" do
      it "assigns the revaluation_act as @revaluation_act" do
        revaluation_act = RevaluationAct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RevaluationAct.any_instance.stub(:save).and_return(false)
        put :update, params: {:id => revaluation_act.to_param, :revaluation_act => { "price_type" => "invalid value" }}, session: valid_session
        assigns(:revaluation_act).should eq(revaluation_act)
      end

      it "re-renders the 'edit' template" do
        revaluation_act = RevaluationAct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RevaluationAct.any_instance.stub(:save).and_return(false)
        put :update, params: {:id => revaluation_act.to_param, :revaluation_act => { "price_type" => "invalid value" }}, session: valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested revaluation_act" do
      revaluation_act = RevaluationAct.create! valid_attributes
      expect {
        delete :destroy, params: {:id => revaluation_act.to_param}, session: valid_session
      }.to change(RevaluationAct, :count).by(-1)
    end

    it "redirects to the revaluation_acts list" do
      revaluation_act = RevaluationAct.create! valid_attributes
      delete :destroy, params: {:id => revaluation_act.to_param}, session: valid_session
      response.should redirect_to(revaluation_acts_url)
    end
  end

end
